### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by autonome** [cabbibo/RainbowMembrane#1]
Hi @cabbibo! I'm a Mozilla dev who wants to fork this and change it (and encourage others to do the same).

Is it possible for you to provide a license for this code that will allow that?

Cheers,

Dietrich

**Comment by cabbibo** [comment]
Ahh yea! Let me just make sure the modeler is OK w/ the model being open sourced, and than I'll put it up! is BSD or MIT ok w/ you?

**Comment by cabbibo** [comment]
Added!

**Comment by autonome** [comment]
Yay, thanks!
